name: SkyKYCbCompass
version: ${project.version}
main: org.kycb.skyKYCbCompass.SkyKYCbCompass
api-version: '1.21'

commands:
  compass:
    description: Управление компасом
    usage: /compass <help>
    aliases: [comp, cmp]